# Generated by rust2rpm 26
%bcond_without check

Name:           snx-rs
Version:        2.2.4
Release:        1
Summary:        Rust client for Checkpoint VPN tunnels

SourceLicense:  AGPL-3.0
License:        AGPL-3.0

URL:            https://github.com/ancwrd1/snx-rs
Source:         https://github.com/ancwrd1/snx-rs/archive/refs/tags/v%{version}.tar.gz#/%{name}-%{version}.tar.gz
Source:         http://github.com/ARPA-SIMC/rpm-snx-rs/releases/download/v%{version}/snx-rs-v%{version}-%{release}-vendor.tar.gz

BuildRequires:  cargo-rpm-macros >= 25
# libdbus-sys
BuildRequires: pkgconfig(dbus-1)
# openssl-sys
BuildRequires: pkgconfig(openssl)
# gobject-sys
BuildRequires: pkgconfig(gobject-2.0)
# gdk-sys
BuildRequires: pkgconfig(gdk-3.0)
# webkit2gtk (?)
BuildRequires: pkgconfig(webkit2gtk-4.1)


%global _description %{expand:
Rust client for Checkpoint VPN tunnels.}

%description %{_description}

%prep
%autosetup -n snx-rs-%{version} -p1 -a1
%cargo_prep -v vendor

cat >> .cargo/config.toml <<EOF
[source.isakmp]
git = "https://github.com/ancwrd1/isakmp.git"
replace-with = "vendored-sources"
EOF

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license COPYING
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%doc options.md
%{_bindir}/snx-rs
%{_bindir}/snx-rs-gui
%{_bindir}/snxctl

%changelog
%autochangelog
